# Generated by Django 4.2.4 on 2023-09-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
